<h1>데이터 전처리를 위한 자료형 변환</h1>

In [1]:
import pandas as pd
import numpy as np

DF / Series의 원소의 실제 데이터에 맞게 타입 변환  
현재 타입 확인 속성: dtypes/dtypes  
현재 타입 변경 메소드: 변수명.astype(변환타입명)

In [2]:
#  데이터 준비 및 DF 인스턴스 생성
df = pd.DataFrame({
    "이름": ["김민수", "이서연", "박지훈"],
    "나이": ["20", "21", np.nan],
    "점수": ["85.5", "90.0", "78.5"],
    "가입일": ["2024-01-10", "2024-02-15", "2024-03-01"]
})

In [3]:
# DF 인스턴스 확인
df

    이름   나이    점수         가입일
0  김민수   20  85.5  2024-01-10
1  이서연   21  90.0  2024-02-15
2  박지훈  NaN  78.5  2024-03-01

In [4]:
# DF 인덱스 확인 
df.index

RangeIndex(start=0, stop=3, step=1)

In [5]:
# DF인스턴스 요약 정보
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      object
 1   나이      2 non-null      object
 2   점수      3 non-null      object
 3   가입일     3 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes

In [6]:
# 실제 데이터 일부
df.head(2)

    이름  나이    점수         가입일
0  김민수  20  85.5  2024-01-10
1  이서연  21  90.0  2024-02-15

DF/Series.astype(변환타입)

In [7]:
# # 실제 데이터와 타입이 안맞을 경우 
# # EX) 나이, 점수, 가입일 -> 결측치 있으면 오류
# df["나이"] = df["나이"].astype(int)
# df["점수"] = df["점수"].astype(float)
# df["가입일"] = df["가입일"].astype("datetime64[ns]")

In [8]:
# 실제 데이터와 타입이 안맞을 경우
# EX) 나이, 점수, 가입일
df["나이"] = df["나이"].astype('Int32')
df["점수"] = df["점수"].astype('Float32')
df["가입일"] = df["가입일"].astype("datetime64[ns]") # 권장하지 않음.

In [9]:
df

    이름    나이    점수        가입일
0  김민수    20  85.5 2024-01-10
1  이서연    21  90.0 2024-02-15
2  박지훈  <NA>  78.5 2024-03-01

In [10]:
df.dtypes

이름             object
나이              Int32
점수            Float32
가입일    datetime64[ns]
dtype: object

숫자형으로 변환 함수 >>> pandas.to_numeric(데이터)

In [11]:
#  데이터 준비 및 DF 인스턴스 생성
df = pd.DataFrame({
    "이름": ["김민수", "이서연", "박지훈"],
    "나이": ["20", "21", np.nan],
    "점수": ["85.5", "90.0", "78.5"],
    "가입일": ["2024-01-10", "2024-02-15", "2024-03-01"]
})

In [12]:
df['점수']= pd.to_numeric(df['점수'], downcast='float')

In [13]:
df.dtypes

이름      object
나이      object
점수     float32
가입일     object
dtype: object

날짜/시간 데이터 형변환 >>> pandas.to_datetime(데이터)

In [22]:
# 가입일 데이터 형변환
df['가입일'] = pd.to_datetime(df['가입일'], dayfirst=True, format='mixed')

In [30]:
df.dtypes

이름             object
나이             object
점수            float32
가입일    datetime64[ns]
dtype: object