<h1>데이터 전처리를 위한 필터링</h1>

DF/Series에서 원하는 데이터만 추출  
불린 인덱싱
isin()  
query()

In [7]:
import pandas as pd
import numpy as np


DATA_FILE = '../DATA/학생관리부.xlsx'

df = pd.read_excel(DATA_FILE, header = 2)

In [8]:
df

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
2  이길동   1  7   12
3  박길동   3  1    9
4  최길동   2  1   43

In [24]:
# 특정 조건에 맞는 데이터만 추출. 즉, 필터링.
# 석차 상위 10위까지만 데이터 추출
# 비교 연산으로 T/F로 구성된 Series 완성
b = df[df.columns[-1]] <= 10
b

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [150]:
# 특정 조건에 맞는 데이터만 추출. 즉, 필터링.
# 석차 상위 10위까지만 데이터 추출
# 비교 연산으로 T/F로 구성된 Series 완성
b = df[df.columns[-1]] <= 10
df[b]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
3  박길동   3  1    9

In [ ]:
# 현재 결과를 반대로
df[~b]

    이름  학년  반   석차
2  이길동   1  7   12
4  최길동   2  1   43

In [160]:
df.columns[1], df.columns[-1]

('학년', ' 석차')

In [155]:
# 학년 컬럼
df[df.columns[1]] == 1

0     True
1     True
2     True
3    False
4    False
Name: 학년, dtype: bool

In [159]:
# 석차 컬럼 <= 10
df[df.columns[-1]] <= 10

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [165]:
# 1학년 중에 상위 10위 안에 들어가는 학생 데이터
# 학년 컬럼 == 1, 석차  <= 10
m = (df[df.columns[1]] == 1) & (df[df.columns[-1]] <= 10)

In [166]:
df[m]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1